### ISSUE TITLE
Flexibility of the clonal calling?

### ISSUE THREAD

**Issue by cnk113** [yihan1119/Group_clone#2]
Hi,

I read your paper and was wondering if the distribution/test for clonal calling will hold if the diversity of barcodes/sgRNA is much higher but the barcode/sgRNA number per cell is lower?
So essentially if we had ~5 BCs/sgRNA per cell but the complexity of the library is > 10 million could I still the clonal group calling as is? Or would it need to be tweaked?

Best,
Chang

**Comment by yihan1119** [comment]
Hi Chang, 
Thanks for the question. Based on the results of our power analysis, it can detect serious clonal expansion. For example, if there are more than 3 sgRNAs co-exist in several cells, there may be clonal expansion. 
I suggest random select a portion of cells in you library and perform a test run since the process may take some times.
Please let me know if you have any other questions.

**Comment by cnk113** [comment]
Thank you!

**Comment by cnk113** [comment]
Sorry I had one more question, in terms of low UMI counts (likely arising from ambience) how well does the pairwise comparison handle low UMIs expressed in multiple cells?

**Comment by yihan1119** [comment]
Hello Chang, 
We filtered out the low UMI count cells before running this analysis, since we cannot assure the low UMI count cells are real cells, and we cannot confidently assign the sgRNAs in those potential artifact cells.

**Comment by cnk113** [comment]
I had another followup in regards to the cutoff values; from what I understand it's based on the overlap and I was wondering how lenient the overlap can be? Such as using a cutoff of 0.1 or even higher? I have a higher diversity library and was wondering how high I can push it.

Best,
Chang

**Comment by yihan1119** [comment]
Hello Chang, 
In our dataset, we found that within clone, the overlap rate is about 20~100% (Fig. 1F). 
A side note: The cutoff from provided example script (0.05) is indicating hypergeometric test p-value instead of overlapping rate since we found using p-value as cutoff is easier to draw the threshold. 
Please let me know if you have any question!
